package MiniMar.db.dao;

import MiniMar.db.model.Classes;
import MiniMar.db.model.ClassesExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    long countByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int deleteByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int insertSelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    List<Classes> selectByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    Classes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int updateByExampleSelective(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int updateByExample(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int updateByPrimaryKeySelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 22 17:31:50 MSK 2022
     */
    int updateByPrimaryKey(Classes record);
}